# Sane keybinds profile for rovr
# This profile uses standard keyboard shortcuts familiar to most users.
# Uses arrow keys for navigation and Ctrl modifiers for common actions.

[keybinds]
toggle_pin = ["P"]
toggle_pinned_sidebar = ["S"]
toggle_preview_sidebar = ["I"]
toggle_footer = ["F"]
toggle_menuwrapper = ["M"]
focus_toggle_pinned_sidebar = ["s"]
focus_file_list = ["escape"]
focus_toggle_preview_sidebar = ["i"]
focus_toggle_path_switcher = ["ctrl+l"]
focus_search = ["ctrl+f"]
focus_toggle_processes = ["ctrl+shift+p"]
focus_toggle_clipboard = ["c"]
focus_toggle_metadata = ["m"]
copy = ["ctrl+c"]
paste = ["ctrl+v"]
cut = ["ctrl+x"]
delete = ["delete"]
rename = ["f2"]
new = ["ctrl+n"]
zip = ["ctrl+shift+e"]
unzip = ["ctrl+e"]
copy_path = ["ctrl+shift+c"]
up = ["up"]
down = ["down"]
up_tree = ["left", "backspace"]
down_tree = ["right", "enter"]
page_up = ["pageup"]
page_down = ["pagedown"]
home = ["home"]
end = ["end"]
hist_previous = ["alt+left"]
hist_next = ["alt+right"]
toggle_visual = ["ctrl+space"]
toggle_all = ["ctrl+a"]
toggle_hidden_files = ["ctrl+h"]
select_up = ["shift+up"]
select_down = ["shift+down"]
select_page_up = ["shift+pageup"]
select_page_down = ["shift+pagedown"]
select_home = ["shift+home"]
select_end = ["shift+end"]
tab_next = ["ctrl+tab"]
tab_previous = ["ctrl+shift+tab"]
tab_new = ["ctrl+t"]
tab_close = ["ctrl+w"]
preview_scroll_left = ["left"]
preview_scroll_right = ["right"]
preview_select_left = ["shift+left"]
preview_select_right = ["shift+right"]
show_keybinds = ["f1"]
quit_app = ["ctrl+q", "alt+f4"]
command_palette = "ctrl+p"
suspend_app = ["ctrl+z"]

[keybinds.change_sort_order]
open_popup = ["ctrl+s"]
name = ["n"]
extension = ["e"]
natural = ["t"]
size = ["s"]
created = ["c"]
modified = ["m"]
descending = ["d"]

[keybinds.delete_files]
trash = ["d"]
delete = ["shift+d"]
cancel = ["escape"]

[keybinds.filename_conflict]
overwrite = ["o"]
skip = ["s"]
rename = ["r"]
cancel = ["escape"]
dont_ask_again = ["a"]

[keybinds.file_in_use]
retry = ["r"]
skip = ["s"]
cancel = ["escape"]
dont_ask_again = ["a"]

[keybinds.filter_modal]
exit = ["escape"]
down = ["down"]
up = ["up"]

[keybinds.yes_or_no]
yes = ["y", "enter"]
no = ["n", "escape"]
dont_ask_again = ["a"]

[plugins.zoxide]
keybinds = ["ctrl+d"]

[plugins.editor]
keybinds = ["ctrl+o"]

[plugins.fd]
keybinds = ["ctrl+g"]
