# Vim keybinds profile for rovr
# This profile uses vim-style keyboard shortcuts familiar to vim users.
# Uses h/j/k/l for navigation and vim-style shortcuts for common actions.

[keybinds]
toggle_pin = ["P"]
toggle_pinned_sidebar = ["S"]
toggle_preview_sidebar = ["I"]
toggle_footer = ["F"]
toggle_menuwrapper = ["M"]
focus_toggle_pinned_sidebar = ["s"]
focus_file_list = ["escape"]
focus_toggle_preview_sidebar = ["i"]
focus_toggle_path_switcher = ["ctrl+l"]
focus_search = ["slash"]
focus_toggle_processes = ["#"]
focus_toggle_clipboard = ["c"]
focus_toggle_metadata = ["m"]
copy = ["y"]
paste = ["p"]
cut = ["x"]
delete = ["d"]
rename = ["r"]
new = ["o"]
zip = ["E"]
unzip = ["ctrl+e"]
copy_path = ["Y"]
up = ["k", "up"]
down = ["j", "down"]
up_tree = ["h", "left"]
down_tree = ["l", "right", "enter"]
page_up = ["ctrl+b", "pageup"]
page_down = ["ctrl+f", "pagedown"]
home = ["g"]
end = ["G"]
hist_previous = ["u", "backspace"]
hist_next = ["ctrl+r", "space"]
toggle_visual = ["v"]
toggle_all = ["%", "ctrl+a"]
toggle_hidden_files = ["full_stop"]
select_up = ["K", "shift+up"]
select_down = ["J", "shift+down"]
select_page_up = ["shift+pageup"]
select_page_down = ["shift+pagedown"]
select_home = ["shift+home"]
select_end = ["shift+end"]
tab_next = ["ctrl+j", "gt"]
tab_previous = ["ctrl+k", "gT"]
tab_new = ["n"]
tab_close = ["w"]
preview_scroll_left = ["h", "left"]
preview_scroll_right = ["l", "right"]
preview_select_left = ["H", "shift+left"]
preview_select_right = ["L", "shift+right"]
show_keybinds = ["?"]
quit_app = ["q", "ctrl+q"]
command_palette = "ctrl+p"
suspend_app = ["ctrl+z"]

[keybinds.change_sort_order]
open_popup = [","]
name = ["a"]
extension = ["e"]
natural = ["n"]
size = ["s"]
created = ["c"]
modified = ["m"]
descending = ["d"]

[keybinds.delete_files]
trash = ["d"]
delete = ["x"]
cancel = ["c", "escape"]

[keybinds.filename_conflict]
overwrite = ["o"]
skip = ["s"]
rename = ["r"]
cancel = ["c", "escape"]
dont_ask_again = ["a"]

[keybinds.file_in_use]
retry = ["r"]
skip = ["s"]
cancel = ["c", "escape"]
dont_ask_again = ["a"]

[keybinds.filter_modal]
exit = ["escape"]
down = ["j", "ctrl+j", "down"]
up = ["k", "ctrl+k", "up"]

[keybinds.yes_or_no]
yes = ["y"]
no = ["n", "escape"]
dont_ask_again = ["a"]

[plugins.zoxide]
keybinds = ["z"]

[plugins.editor]
keybinds = ["e"]

[plugins.fd]
keybinds = ["f"]
