name: Build with Nuitka

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            name: windows-x64
            executable: rovr.exe
          - os: windows-11-arm
            name: windows-arm
            executable: rovr.exe
          - os: ubuntu-latest
            name: linux-x64
            executable: rovr.bin
          - os: ubuntu-24.04-arm
            name: linux-arm64
            executable: rovr.bin
          - os: macos-latest
            name: macos-arm64
            executable: rovr.bin
          - os: macos-15
            name: macos-x64
            executable: rovr.bin

    runs-on: ${{ matrix.os }}
    name: Build (${{ matrix.name }})

    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
          python-version: "3.12"

      - name: Cache Nuitka
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/Nuitka
            ~/AppData/Local/Nuitka/Nuitka
            ~/Library/Caches/Nuitka
          key: nuitka-${{ matrix.name }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            nuitka-${{ matrix.name }}-

      - name: Install dependencies
        run: uv sync --dev

      - name: Build with Nuitka (onefile)
        run: |
          uv run poe build

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          path: ${{ matrix.executable }}
          name: rovr-${{ matrix.name }}
          retention-days: 30
      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1.13.0
        with:
          webhook: ${{ secrets.LOG_HOOK }}
          title: rovr ci build is complete!
          status: ${{ job.status }}
          description: |
            Matrix ${{ matrix.name }} finished compiling!
            Click [here](https://nightly.link/NSPC911/rovr/actions/runs/${{ github.run_id }}/rovr-${{ matrix.name }}.zip) to download!
            -# caused by ${{ github.actor }}
          avatar_url: "https://avatars.githubusercontent.com/u/176916861?v=4"
          username: "NSPBot911"
          nodetail: true
          notimestamp: true
          noprefix: true
