name: Build with Nuitka

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup uv
      uses: astral-sh/setup-uv@v6
      with:
        activate-environment: true
        python-version: "3.12"

    - name: Install dependencies
      run: |
        uv sync --dev
      shell: pwsh

    - name: Build with Nuitka (standalone)
      run: |
        uv run nuitka --mode=standalone --assume-yes-for-downloads --enable-plugins=no-qt --python-flag=-m src/rovr --include-package-data=rovr
      shell: pwsh

    - name: List dist items
      run: Get-ChildItem -Recurse .\rovr.dist
      shell: pwsh

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: rovr_windows_build
        path: rovr.dist
        retention-days: 30

    - name: Build with Nuitka (onefile)
      run: |
        uv run nuitka --mode=onefile --assume-yes-for-downloads --enable-plugins=no-qt --python-flag=-m src/rovr --include-package-data=rovr
      shell: pwsh

    - name: Upload Onefile Executable
      uses: actions/upload-artifact@v4
      # upload executable at ./rovr.exe
      with:
        path: rovr.exe
        name: rovr_windows_onefile_build
        retention-days: 30
